### PR TITLE
Scrcpy Output after input

### PR DESCRIPTION
**Pull request by jaxparrow07**
Silencing `scrcpy` will only silent the first output. The next output lines are printed in the input and after the input. Removed silent command.

### CODE REVIEW

**Comment by enty8080** [comment]
@jaxparrow07 I can't merge this because it conflicts with base branch. Can you add Streaming Android Webcam option to Ghost Framework (I do not know how to do this)?

**Comment by jaxparrow07** [comment]
@enty8080 Also, I am new to Github. Idk how to remove the conflicts with it. I am planning to add, webcam and audio capture.

**Comment by enty8080** [comment]
@jaxparrow07 To fix conflict you should re-fork repository. Remove your ghost and create new fork.

**Comment by jaxparrow07** [comment]
I fixed it bro. I am a developer from Androidx86. I know something about adb and android shell. That's why I am contributing.

**Pull request closed without merging**
