### PR TITLE
Add adb install string for kali. [Working in kali linux]

### PR DESCRIPTION
**Pull request by pranaypaine**

### CODE REVIEW

**Comment by enty8080** [comment]
Hmm, apt-get automatically installs android-adb and android-fastboot if you type `apt-get install adb`

**Comment by pranaypaine** [comment]
`apt-get install adb` works with other debian based Linux distros.
But I got this in kali, maybe there is some corner case in kali.
Are you able to start ghost in kali using `install.sh`
I'm using kali Linus 2020.1 Virtualbox image.

**Comment by enty8080** [comment]
I am using kali 2020.1 and everything is ok.

**Comment by RaghavSom** [comment]
i have also got the same problem and I'm using kali linux 2020.1b
image

**Comment by RaghavSom** [comment]
please tell me any solution for this

**Comment by pranaypaine** [comment]
@RaghavSom try this command
`apt-get -y install android-tools-adb`
this worked for me.

**Comment by enty8080** [comment]
Seriously????????? @RaghavSom , you don't have apt repos installed

**Comment by enty8080** [comment]
See /etc/apt/sources.list

**Comment by RaghavSom** [comment]
Failed to connect to target ip
image
please suggest something
how to do it

**Comment by Sohaib219** [comment]
I have problem ( unable to locate package adb )

**Comment by king5300** [comment]
Shpvj

**Review by king5300 — APPROVED** [review]
Hd

**Review by king5300 — APPROVED** [review]
Zd

**Pull request closed without merging**
